### ISSUE TITLE
VUX 3.0 Roadmap

### ISSUE THREAD

**Issue by airyland** [airyland/vux#1346]
- [ ] 免声明使用组件

  在每个页面进行 import 是个重复浪费时间的事，所以组织决定了，3.0 以后可以实现无须引入就可以在 template 里使用组件了。依然是按需使用。如果没有使用代码分割，会自动在 main.js 自动注册使用到的组件。如果使用代码分割，只要简单配置，就可以实现比如超过两个页面使用的组件自动全局组件，其他情况仅在当前页面注册。

   附带的功能是如果你希望像其他组件库一样组件名字有个统一前缀，避免跟其他组件混淆，你可以配置个喜欢的前缀，比如 `vux-`。

- [x] 适配服务端渲染 #785 
- [ ] feature shaking<sup>beta</sup> 一个按行使用组件代码的工程化实践
- [ ] 社区。开放常规讨论区和付费问答区。
- [ ] gist 功能，方便重现及分享你用 VUX 开发的页面。 
- [x] SEO 考虑，文档使用 Vue ssr(ream)

## 表单验证问题

尝试实现整个 group 的统一验证 #1566 #1408

**Comment by Sapphire2k** [comment]
哇塞！很期待！

**Comment by lxalano** [comment]
期待，vux在ios上的体验很不错，在安卓上的体验还是需要优化啊，总感觉有些迟钝！

**Comment by dengdan99** [comment]
666

**Comment by wg5945** [comment]
good！

**Comment by guntertien** [comment]
非常好，大力支持

**Comment by Kyncc** [comment]
double click six six six

**Comment by nali946** [comment]
six six six

**Comment by colmugx** [comment]
666

**Comment by jinchaoxiang** [comment]
nice

**Comment by murmurwoodz** [comment]
值得期待，不枉我到处安利

**Comment by wg5945** [comment]
是否考虑升级一下vue的版本，比如2.3中sync的回归

**Comment by airyland** [comment]
@wg5945 vue 版本是取决于用户端的。VUX 如果用到 sync 就得要求用户使用新版本时必须升级到 2.3，这会造成兼容问题。考虑一下是否有哪些组件需要用到 sync。

**Comment by wg5945** [comment]
@airyland 
比如像一些弹出控件的show，就不需要再搞个currentValue出来了，直接使用value

例如XDialog，可以简化成
```
<template>
  <div class="vux-x-dialog" @touchmove="onTouchMove">
    <transition :name="maskTransition">
      <div class="weui-mask" @click="hideOnBlur && $emit('update:value', false)" v-show="value"></div>
    </transition>
    <transition :name="dialogTransition">
      <div class="weui-dialog" v-show="value" :style="dialogStyle">
        <slot></slot>
      </div>
    </transition>
  </div>
</template>
```

currentValue和watch里面一大堆就可以删除了

**Comment by airyland** [comment]
@wg5945 这确实是一坑。这些代码都不忍直视了。

**Comment by wg5945** [comment]
这个如果要搞的话，就是非兼容性更新了，建议大版本更新的时候搞一下

我看element在1.3版本更新的时候做了这个

**Comment by yezongyang** [comment]
@airyland 
3.0 版 关于样式是否再灵活些，比如tab里的分隔线是背景，改成用伪类是否更好。还有诸如内联样式的涉及到固定像素的最好提到样式文件里

**Comment by airyland** [comment]
@yezongyang 可以 pr。

**Comment by jjjachyty** [comment]
建议把group 的验证做一下

**Comment by PlusLius** [comment]
赞一个,希望作者更新后,能够做到组件按需引入,能够优化打包后的体积

**Comment by airyland** [comment]
@PlusLius 2.0 默认就是按需引入了，难道你一直都是全部打包？

**Comment by F5F5** [comment]
@airyland 请问3.0计划大概什么时候上呢？

**Comment by yuezheng2006** [comment]
webpack3配合vux-loader 使用过程中发现,extract-text-plugin功能失效 并且也没有错误日志输出,有遇到过这个问题么

**Comment by fuerpeng** [comment]
我喜欢表单验证

**Comment by RenShine** [comment]
赞一个  喜欢免声明引入  之前我还提了一个issuse想要这功能

**Comment by ClassEve** [comment]
这个厉害了

**Comment by aladdin-add** [comment]
* 希望能有基本的单元测试 -- 有影响力的组件库应该有一个好的引导。
* 包发布编译后的版本(umd, esm)，现在的方式给用户很大的配置负担。

**Comment by 623023808** [comment]
使用代码分割时什么意思？希望作者可以再优化下侧边栏&抽屉drawer，使其可以滑动打开或关闭。希望vux早日名扬国际

**Comment by rochzp** [comment]
能否在picker组件中增加一个显示行数的属性啊，还有popup-picker、datetime等

**Comment by 623023808** [comment]
vux 组件样式重复又解决方法吗

**Comment by chen-jiajian** [comment]
良心框架，更新速度很快呀

**Comment by lyh2668** [comment]
抛弃了mint-ui选择vux，mint-ui的代码质量虽然还挺不错，但是组件少了点，更新慢了点，issues的处理也明显慢了，而在这里看到vux作者效率得更新及处理issues，让我们用户用的安心，赞一个。

**Comment by olunx** [comment]
可能，我说可能。有没有可能支持weex。。。

**Comment by airyland** [comment]
@olunx 这个不可能。这种花大量时间没有回报的事还是留给大团队来做。。

**Comment by olunx** [comment]
@airyland 好哒。~~~~(>_<)~~~~

**Comment by Jiiiiiin** [comment]
阔以阔以 😸 弱弱问一句[使用案例](https://vux.li/#/?id=使用案例)还接受更新吗 @airyland  哈哈。
